from enum import IntEnum

class ExitCode(IntEnum):
    DATA_FORMAT_ERROR = -1
    BSS_FORMAT_ERROR = -2
    CONSTANT_DECLARATION_ERROR = -3
    NO_START_LABEL = 1
    DUPLICATE_LABEL = 2
    UNOPENABLE_FILE = 4
    STACK_OVERFLOW = 5
    INVALID_INSTRUCTION_SYNTAX = 10
    SOFTWARE_ERROR = 109101
    # To be continued later